routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::namespace('Backend')->group(function () {
  
  Route::post('/payment/response', 'PaymentController@handle')->name('payment.response');
});

Route::middleware(['auth'])->prefix('admin')->namespace('Backend')->name('admin.')->group(function() {
  
  Route::get('/', 'DashboardController@index')->name('index');
  Route::get('/setting', 'SettingController@index')->name('setting.index');
  Route::post('/setting/store', 'SettingController@store')->name('setting.store');
  Route::post('/setting/setwebhook', 'SettingController@setwebhook')->name('setting.setwebhook');
  Route::post('/setting/getwebhookinfo', 'SettingController@getwebhookinfo')->name('setting.getwebhookinfo');

  Route::resource('/telegramuser', 'TelegramUserController');
  Route::resource('/product', 'ProductController');
  Route::resource('/order', 'OrderController');

  Route::get('/notice/user/{order}', 'NoticeController@notice_user')->name('notice.user');
});

Auth::routes();

Route::match(['post', 'get'], 'register', function() {
  Auth::logout();
  return redirect('/');
})->name('register');

app/Http/Controllers/Backend/ChatController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Chat;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ChatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Chat  $chat
     * @return \Illuminate\Http\Response
     */
    public function show(Chat $chat)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Chat  $chat
     * @return \Illuminate\Http\Response
     */
    public function edit(Chat $chat)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Chat  $chat
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Chat $chat)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Chat  $chat
     * @return \Illuminate\Http\Response
     */
    public function destroy(Chat $chat)
    {
        //
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Order;
use App\TelegramUser;
use App\Product;

class DashboardController extends Controller
{
    //
    public function index() {
      
      return view('backend.index', [
        'products' => count(Product::all()->toArray()),
        'users'    => count(TelegramUser::all()->toArray()),
        'orders'   => count(Order::all()->toArray()),
      ]);
    }
}

app/Http/Controllers/Backend/MadelineController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MadelineController extends Controller
{
  public function index() {
   
    dd(env('TELEGRAM_SESSION_FILE'));
    if(file_exists( env('TELEGRAM_SESSION_FILE') ) ) {
      $madeline = new \danog\MadelineProto\API( env('TELEGRAM_SESSION_FILE') );
      $Chat = $MadelineProto->get_pwr_chat('-1001241127407');
      dd($Chat);
    } else {
      echo 'Config file don\'t exist';
    }
  }
}

app/Http/Controllers/Backend/NoticeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Telegram\Bot\Keyboard\Keyboard;
use Telegram\Bot\Api;
use App\Product;
use App\Order;
use App\TelegramUser;
use App\Setting;
use Mail;

class NoticeController extends Controller
{
 
  /**
   * Notice admin 
   */
  public static function vebinar_paid(Order $order)
  {
   
    $url   = \URL::to('/') . '/admin/order/' . $order->id . '/edit';
    $email = Setting::getSettings('admin_email');
    $email = ($email) ? $email->value : 0;
    $data  = [
      'url' => $url
    ];

    \Log::info('email');
    \Log::info(print_r($email, true));

    Mail::send('emails.welcome', $data, function ($message) use ($email) {
      $message->to($email);
    });
  }

  /**
   * Notice users when subscription expires
   */
  public static function subscription_expires() {

    $telegram = new Api(env('TELEGRAM_BOT_TOKEN'));
    $now      = new \DateTime();
    $last_pay = $now->modify('-28 day');
    $last_pay = $last_pay->format('Y-m-d');
    $users    = TelegramUser::whereDate('subscribe_date', '=', $last_pay)->where('in_chat', '=', 1)->where('sub_notice', '=', 0)->take(5)->get();

    foreach($users as $user) {

      $user->sub_notice = 1;
      $user->save();

      $reply_markup = new Keyboard();
      $reply_markup->inline();

      $subscription_cost = Setting::getSettings('subscription_cost');
      $subscription_cost = ($subscription_cost) ? $subscription_cost->value : 0;
      $merchant_id       = Setting::getSettings('merchant_id');
      $merchant_id       = ($merchant_id) ? $merchant_id->value : 0;
      $secret_word       = 'ignetdapassion';
      $sign              = md5($merchant_id.':'.$subscription_cost.':'.$secret_word.':'.$user->id);

      $text  = sprintf('%s' . PHP_EOL, 'Срок действия вашей подписки истекает через три дня');
      $text .= sprintf('%s' . PHP_EOL, 'Стоимость: ' . $subscription_cost . ' руб/мес');
      $url   = 'http://www.free-kassa.ru/merchant/cash.php?' . 'm=' . $merchant_id . '&oa=' . $subscription_cost . '&o=' . $user->id . '&s=' . $sign . '&us_type=subscribe';  

      $sub_btn = Keyboard::inlineButton([
        'text' => 'Оплатить',
        'url'  => $url,
      ]);

      $reply_markup->row(
        $sub_btn
      );
  
      $telegram->sendMessage([
        'chat_id'      => $user->id,
        'text'         => $text,
        'reply_markup' => $reply_markup
      ]);
    }
  }

  /**
   * Notice users when subscription expired
   */
  public static function subscription_expired() {

    $telegram = new Api(env('TELEGRAM_BOT_TOKEN'));
    $now      = new \DateTime();
    $last_pay = $now->modify('-30 day');
    $last_pay = $last_pay->format('Y-m-d');
    $users    = TelegramUser::whereDate('subscribe_date', '<', $last_pay)->where('in_chat', '=', 1)->take(5)->get();

    foreach($users as $user) {

      $subscription_cost = Setting::getSettings('subscription_cost');
      $subscription_cost = ($subscription_cost) ? $subscription_cost->value : 0;
      $chat_id           = Setting::getSettings('chat_id');
      $chat_id           = ($chat_id) ? $chat_id->value : 0;

      if ( ! $chat_id) {
        return;
      }

      $user->in_chat = 0;
      $user->save();

      $merchant_id       = Setting::getSettings('merchant_id');
      $merchant_id       = ($merchant_id) ? $merchant_id->value : 0;
      $secret_word       = 'ignetdapassion';
      $sign              = md5($merchant_id.':'.$subscription_cost.':'.$secret_word.':'.$user->id);

      $text  = sprintf('%s' . PHP_EOL, 'Срок действия вашей подписки истек. Вы были удалены из чата.');
      $text .= sprintf('%s' . PHP_EOL, 'Чтобы вступить в чат оплатите подписку.');
      $text .= sprintf('%s' . PHP_EOL, 'Стоимость: ' . $subscription_cost . ' руб/мес');
      $url   = 'http://www.free-kassa.ru/merchant/cash.php?' . 'm=' . $merchant_id . '&oa=' . $subscription_cost . '&o=' . $user->id . '&s=' . $sign . '&us_type=subscribe';  

      $telegram->kickChatMember([
        'chat_id' => $chat_id,
        'user_id' => $user->id
      ]);

      $reply_markup = new Keyboard();
      $reply_markup->inline();

      $sub_btn = Keyboard::inlineButton([
        'text' => 'Оплатить',
        'url'  => $url,
      ]);

      $reply_markup->row(
        $sub_btn
      );
  
      $telegram->sendMessage([
        'chat_id'      => $user->id,
        'text'         => $text,
        'reply_markup' => $reply_markup
      ]);
    }
  }

  /**
   * Notice users when subscription paid successfully
   */
  public static function subscription_paid($user) {

    $telegram  = new Api(env('TELEGRAM_BOT_TOKEN'));
    $chat_id   = Setting::getSettings('chat_id');
    $chat_id   = ($chat_id) ? $chat_id->value : 0;
    $telegram  = new Api(env('TELEGRAM_BOT_TOKEN'));
    $chat_link = Setting::getSettings('chat_link');
    $chat_link = ($chat_link) ? $chat_link->value : 0;
    $text      = 'Вы успешно оплатили подписку.' . PHP_EOL;

    if ( ! $user->in_chat) {

      $telegram->unbanChatMember([
        'chat_id' => $chat_id,
        'user_id' => $user->id
      ]);

      $text .= 'Ссылка на вступление в чат: ' . $chat_link . PHP_EOL;
    }

    $telegram->sendMessage([
      'chat_id'      => $user->id,
      'text'         => $text
    ]);

    $text = 'Выберите действие';

    $vebinar_buy = Keyboard::inlineButton([
      'text'          => 'Купить вебинары',
      'callback_data' => 'buy_vebinars',
    ]);

    $my_vebinars = Keyboard::inlineButton([
      'text'          => 'Мои покупки',
      'callback_data' => 'my_vebinars',
    ]);

    $reply_markup = new Keyboard();
    $reply_markup->inline();
    $reply_markup->row(
      $vebinar_buy,
      $my_vebinars
    );

    $response = $telegram->sendMessage([
      'chat_id'      => $query->getFrom()->getId(),
      'text'         => $text,
      'reply_markup' => $reply_markup
    ]);
  }

  /**
   * Send vebinar link to user
   */
  public function notice_user(Order $order) {

    $telegram = new Api(env('TELEGRAM_BOT_TOKEN'));
    $products = unserialize($order->products);
    $product  = $products[0];
    $vebinar  = Product::find($product);

    $text  = 'Вы оплатили вебинар "' . $vebinar->title .'"' . PHP_EOL;
    $text .= 'Ссылка на вебинар: ' . $order->description .'"' . PHP_EOL;

    $telegram->sendMessage([
      'chat_id' => $order->telegram_user_id,
      'text'    => $text
    ]);

    $text = 'Выберите действие';

    $vebinar_buy = Keyboard::inlineButton([
      'text'          => 'Купить вебинары',
      'callback_data' => 'buy_vebinars',
    ]);

    $my_vebinars = Keyboard::inlineButton([
      'text'          => 'Мои покупки',
      'callback_data' => 'my_vebinars',
    ]);

    $reply_markup = new Keyboard();
    $reply_markup->inline();
    $reply_markup->row(
      $vebinar_buy,
      $my_vebinars
    );

    $response = $telegram->sendMessage([
      'chat_id'      => $order->telegram_user_id,
      'text'         => $text,
      'reply_markup' => $reply_markup
    ]);

    return redirect()->route('admin.order.edit', $order);
  }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Order;
use App\TelegramUser;
use App\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {

    $users_data = [];
    $users      = TelegramUser::all()->toArray();
    foreach ($users as $user) {

      $users_data[ $user['id'] ] = $user['first_name'] . ' ' . $user['last_name'];
    } 
      
    return view('backend.orders.index', [
      'orders' => Order::orderBy('created_at', 'desc')->paginate(7),
      'users'  => $users_data
    ]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    
    return view('backend.orders.create', [
      'order'    => [],
      'users'    => TelegramUser::all()->toArray(),
      'products' => Product::where('status', '=', 1)->get()->toArray()
    ]);
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    
    $order = Order::create($request->all());

    return redirect()->route('admin.order.edit', $order);
  }

  /**
   * Display the specified resource.
   *
   * @param  \App\Order  $order
   * @return \Illuminate\Http\Response
   */
  public function show(Order $order)
  {
    
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  \App\Order  $order
   * @return \Illuminate\Http\Response
   */
  public function edit(Order $order)
  {
    return view('backend.orders.edit', [
      'order'    => $order,
      'users'    => TelegramUser::all()->toArray(),
      'products' => Product::all()->toArray()
    ]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  \App\Order  $order
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Order $order)
  {
    $order->update($request->except('slug'));

    return redirect()->route('admin.order.edit', $order);
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  \App\Order  $order
   * @return \Illuminate\Http\Response
   */
  public function destroy(Order $order)
  {
    $order->delete();
    
    return redirect()->route('admin.order.index');
  }
}

app/Http/Controllers/Backend/PaymentController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Setting;
use App\Order;
use App\TelegramUser;
use App\Product;

class PaymentController extends Controller
{
  public function handle() {

    // http://77.222.60.8/payment/response?MERCHANT_ID=97957&AMOUNT=15.30&MERCHANT_ORDER_ID=1&SIGN=dgd&us_type=vebiinar

    \Log::info('test');
    \Log::info(print_r($_REQUEST, true));

    $available_ip = ['136.243.38.147', '136.243.38.149', '136.243.38.150', '136.243.38.151', '136.243.38.189', '88.198.88.98'];
    $ip           = isset($_SERVER['HTTP_X_REAL_IP']) ? $_SERVER['HTTP_X_REAL_IP'] : $_SERVER['REMOTE_ADDR'];
    if ( ! in_array($ip, $available_ip)) {
     die('hacking attempt!');
    }

    $merchant_id = Setting::getSettings('merchant_id');
    $merchant_id = ($merchant_id) ? $merchant_id->value : 0;
    $secret_word = 'ignetdapassion';

    $sign = md5($merchant_id.':'.$_REQUEST['AMOUNT'].':'.$secret_word.':'.$_REQUEST['MERCHANT_ORDER_ID']);

    if ($sign != $_REQUEST['SIGN']) {
      die('wrong sign');
    }

    if ( ! isset($_REQUEST['us_type'])) {

      die('wrong request');
    }

    $type     = $_REQUEST['us_type'];
    $amount   = $_REQUEST['AMOUNT'];
    $order_id = $_REQUEST['MERCHANT_ORDER_ID'];

    if ('subscribe' == $type) {

      $subscription_cost = Setting::getSettings('subscription_cost');
      $subscription_cost = ($subscription_cost) ? $subscription_cost->value : 0;
      if ($subscription_cost != $amount) {
        die('wrong amount');
      }

      $teluser = TelegramUser::find($_REQUEST['MERCHANT_ORDER_ID']);
      if ( ! $teluser) {
        die('wrong user id');
      }

      $now = new \DateTime();
      $now->format('Y-m-d H:i:s');

      $teluser->subscribe_date = $now;
      $teluser->sub_notice     = 0;
      $teluser->save();

      NoticeController::subscription_paid($teluser);
    } else {

      $order = Order::find($_REQUEST['MERCHANT_ORDER_ID']);
      if ( ! $order) {
        die('wrong order id');
      }

      if (floatval($amount) < floatval($order->amount)) {
        die('wrong amount');
      }
      
      $order->status = 1;
      $order->save();

      $products      = unserialize($order->products);
      $teluser       = TelegramUser::find($order->telegram_user_id);
      $paid_products = unserialize($teluser->products);
      $paid_products = ( ! is_array($paid_products)) ? [] : $paid_products;
      $result        = array_unique(array_merge($products, $paid_products));

      $teluser->products = serialize($result);
      $teluser->save();

      NoticeController::vebinar_paid($order);
    }

    die('ok');
  }
}

resources/views/backend/index.blade.php
@extends('backend.layouts.app')

@section('content')

  <div class="container">
    <h1>Dashboard</h1>
    <br>
    <div class="row">

      <div class="col-md-4">
        <div class="panel panel-info">
            <div class="panel-heading">Users</div>
          <div class="panel-body">
            <p>Count: {{ $users }}</p>
            <a href="{{ route('admin.telegramuser.index') }}">View All Users</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel panel-info">
            <div class="panel-heading">Products</div>
          <div class="panel-body">
              <p>Count: {{ $products }}</p>
              <a href="{{ route('admin.product.index') }}">View All Products</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel panel-info">
            <div class="panel-heading">Orders</div>
          <div class="panel-body">
              <p>Count: {{ $orders }}</p>
              <a href="{{ route('admin.order.index') }}">View All Orders</a>
              
          </div>
        </div>
      </div>

    </div>

     
  </div>
@endsection

resources/views/backend/madeline.blade.php
<h1>Hello</h1>

resources/views/backend/setting.blade.php
@extends('backend.layouts.app')

@section('content')

<div class="container">
@if (Session::has('status'))
  <div class="alert alert-info">
    <span>{{ Session::get('status') }}</span>
  </div>
@endif

<form action="{{ route('admin.setting.store') }}" method="post">
  {{ csrf_field() }}
  <div class="form-group">
    <label>Url callback for Telegram</label>
    <div class="input-group">
      <div class="input-group-btn">
        <button type="button" class="btn btn-default dropdowm-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><a href="#" onclick="document.getElementById('url_callback_bot').value = '{{ url('') }}'"> Вставить url</a></li>
          <li><a href="#" onclick="event.preventDefault(); document.getElementById('setwebhook').submit();">Отправить url</a></li>
          <li><a href="#" onclick="event.preventDefault(); document.getElementById('getwebhookinfo').submit();"> Получить информацию</a></li>
        </ul>
      </div>
      <input type="url" class="form-control" id="url_callback_bot" name="url_callback_bot" value="{{ $url_callback_bot or '' }}" required>
    </div>
  </div>
  <div class="form-group">
    <label>Admin email</label>
    <div class="input-group">
      <input type="email" class="form-control" id="admin_email" name="admin_email" value="{{ $admin_email or '' }}" required>
    </div>
  </div>
  <div class="form-group">
    <label>Merchant id</label>
    <div class="input-group">
      <input type="number" class="form-control" id="merchant_id" name="merchant_id" value="{{ $merchant_id or '' }}" required>
    </div>
  </div>
  <div class="form-group">
    <label>Subscription cost</label>
    <div class="input-group">
      <input type="number" class="form-control" id="subscription_cost" name="subscription_cost" value="{{ $subscription_cost or '' }}" required>
    </div>
  </div>
  <div class="form-group">
    <label>Invite chat link</label>
    <div class="input-group">
      <input type="url" class="form-control" id="chat_link" name="chat_link" value="{{ $chat_link or '' }}" required>
    </div>
  </div>
  <div class="form-group">
    <label>Chat</label>
    <div class="input-group">
      <select name="chat_id" class="form-control">
        @if (isset($chat_id))

          @foreach ($chats as $chat)
            <option value="{{ $chat['id'] }}" @if ($chat['id'] == $chat_id) selected="" @endif> {{ $chat['title'] }}</option>
          @endforeach
        @else

          @foreach ($chats as $chat)
            <option value="{{ $chat['id'] }}"> {{ $chat['title'] }}</option>
          @endforeach
        @endif
      </select>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Сохранить</button>
</form>

<form action="{{ route('admin.setting.setwebhook') }}" id="setwebhook" method="post" style="display: none;">
  {{ csrf_field() }}
  <input type="hidden" name="url" value="{{ $url_callback_bot or '' }}">
</form>
  
<form action="{{ route('admin.setting.getwebhookinfo') }}" id="getwebhookinfo" method="post" style="display: none;">
  {{ csrf_field() }}
</form>
  
</div>

@endsection