routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::namespace('Backend')->group(function () {
  
  Route::post('/payment/response', 'PaymentController@handle')->name('payment.response');
});

Route::middleware(['auth'])->prefix('admin')->namespace('Backend')->name('admin.')->group(function() {
  
  Route::get('/', 'DashboardController@index')->name('index');
  Route::get('/setting', 'SettingController@index')->name('setting.index');
  Route::post('/setting/store', 'SettingController@store')->name('setting.store');
  Route::post('/setting/setwebhook', 'SettingController@setwebhook')->name('setting.setwebhook');
  Route::post('/setting/getwebhookinfo', 'SettingController@getwebhookinfo')->name('setting.getwebhookinfo');

  Route::resource('/telegramuser', 'TelegramUserController');
  Route::resource('/product', 'ProductController');
  Route::resource('/order', 'OrderController');

  Route::get('/notice/user/{order}', 'NoticeController@notice_user')->name('notice.user');
});

Auth::routes();

Route::match(['post', 'get'], 'register', function() {
  Auth::logout();
  return redirect('/');
})->name('register');

app/Http/Controllers/Backend/ChatController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Chat;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ChatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Chat  $chat
     * @return \Illuminate\Http\Response
     */
    public function show(Chat $chat)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Chat  $chat
     * @return \Illuminate\Http\Response
     */
    public function edit(Chat $chat)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Chat  $chat
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Chat $chat)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Chat  $chat
     * @return \Illuminate\Http\Response
     */
    public function destroy(Chat $chat)
    {
        //
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Order;
use App\TelegramUser;
use App\Product;

class DashboardController extends Controller
{
    //
    public function index() {
      
      return view('backend.index', [
        'products' => count(Product::all()->toArray()),
        'users'    => count(TelegramUser::all()->toArray()),
        'orders'   => count(Order::all()->toArray()),
      ]);
    }
}

app/Http/Controllers/Backend/MadelineController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MadelineController extends Controller
{
  public function index() {
   
    dd(env('TELEGRAM_SESSION_FILE'));
    if(file_exists( env('TELEGRAM_SESSION_FILE') ) ) {
      $madeline = new \danog\MadelineProto\API( env('TELEGRAM_SESSION_FILE') );
      $Chat = $MadelineProto->get_pwr_chat('-1001241127407');
      dd($Chat);
    } else {
      echo 'Config file don\'t exist';
    }
  }
}

app/Http/Controllers/Backend/NoticeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Telegram\Bot\Keyboard\Keyboard;
use Telegram\Bot\Api;
use App\Product;
use App\Order;
use App\TelegramUser;
use App\Setting;
use Mail;

class NoticeController extends Controller
{
 
  /**
   * Notice admin 
   */
  public static function vebinar_paid(Order $order)
  {
   
    $url   = \URL::to('/') . '/admin/order/' . $order->id . '/edit';
    $email = Setting::getSettings('admin_email');
    $email = ($email) ? $email->value : 0;
    $data  = [
      'url' => $url
    ];

    \Log::info('email');
    \Log::info(print_r($email, true));

    Mail::send('emails.welcome', $data, function ($message) use ($email) {
      $message->to($email);
    });
  }

  /**
   * Notice users when subscription expires
   */
  public static function subscription_expires() {

    $telegram = new Api(env('TELEGRAM_BOT_TOKEN'));
    $now      = new \DateTime();
    $last_pay = $now->modify('-28 day');
    $last_pay = $last_pay->format('Y-m-d');
    $users    = TelegramUser::whereDate('subscribe_date', '=', $last_pay)->where('in_chat', '=', 1)->where('sub_notice', '=', 0)->take(5)->get();

    foreach($users as $user) {

      $user->sub_notice = 1;
      $user->save();

      $reply_markup = new Keyboard();
      $reply_markup->inline();

      $subscription_cost = Setting::getSettings('subscription_cost');
      $subscription_cost = ($subscription_cost) ? $subscription_cost->value : 0;
      $merchant_id       = Setting::getSettings('merchant_id');
      $merchant_id       = ($merchant_id) ? $merchant_id->value : 0;
      $secret_word       = 'ignetdapassion';
      $sign              = md5($merchant_id.':'.$subscription_cost.':'.$secret_word.':'.$user->id);

      $text  = sprintf('%s' . PHP_EOL, 'Срок действия вашей подписки истекает через три дня');
      $text .= sprintf('%s' . PHP_EOL, 'Стоимость: ' . $subscription_cost . ' руб/мес');
      $url   = 'http://www.free-kassa.ru/merchant/cash.php?' . 'm=' . $merchant_id . '&oa=' . $subscription_cost . '&o=' . $user->id . '&s=' . $sign . '&us_type=subscribe';  

      $sub_btn = Keyboard::inlineButton([
        'text' => 'Оплатить',
        'url'  => $url,
      ]);

      $reply_markup->row(
        $sub_btn
      );
  
      $telegram->sendMessage([
        'chat_id'      => $user->id,
        'text'         => $text,
        'reply_markup' => $reply_markup
      ]);
    }
  }

  /**
   * Notice users when subscription expired
   */
  public static function subscription_expired() {

    $telegram = new Api(env('TELEGRAM_BOT_TOKEN'));
    $now      = new \DateTime();
    $last_pay = $now->modify('-30 day');
    $last_pay = $last_pay->format('Y-m-d');
    $users    = TelegramUser::whereDate('subscribe_date', '<', $last_pay)->where('in_chat', '=', 1)->take(5)->get();

    foreach($users as $user) {

      $subscription_cost = Setting::getSettings('subscription_cost');
      $subscription_cost = ($subscription_cost) ? $subscription_cost->value : 0;
      $chat_id           = Setting::getSettings('chat_id');
      $chat_id           = ($chat_id) ? $chat_id->value : 0;

      if ( ! $chat_id) {
        return;
      }

      $user->in_chat = 0;
      $user->save();

      $merchant_id       = Setting::getSettings('merchant_id');
      $merchant_id       = ($merchant_id) ? $merchant_id->value : 0;
      $secret_word       = 'ignetdapassion';
      $sign              = md5($merchant_id.':'.$subscription_cost.':'.$secret_word.':'.$user->id);

      $text  = sprintf('%s' . PHP_EOL, 'Срок действия вашей подписки истек. Вы были удалены из чата.');
      $text .= sprintf('%s' . PHP_EOL, 'Чтобы вступить в чат оплатите подписку.');
      $text .= sprintf('%s' . PHP_EOL, 'Стоимость: ' . $subscription_cost . ' руб/мес');
      $url   = 'http://www.free-kassa.ru/merchant/cash.php?' . 'm=' . $merchant_id . '&oa=' . $subscription_cost . '&o=' . $user->id . '&s=' . $sign . '&us_type=subscribe';  

      $telegram->kickChatMember([
        'chat_id' => $chat_id,
        'user_id' => $user->id
      ]);

      $reply_markup = new Keyboard();
      $reply_markup->inline();

      $sub_btn = Keyboard::inlineButton([
        'text' => 'Оплатить',
        'url'  => $url,
      ]);

      $reply_markup->row(
        $sub_btn
      );
  
      $telegram->sendMessage([
        'chat_id'      => $user->id,
        'text'         => $text,
        'reply_markup' => $reply_markup
      ]);
    }
  }

  /**
   * Notice users when subscription paid successfully
   */
  public static function subscription_paid($user) {

    $telegram  = new Api(env('TELEGRAM_BOT_TOKEN'));
    $chat_id   = Setting::getSettings('chat_id');
    $chat_id   = ($chat_id) ? $chat_id->value : 0;
    $telegram  = new Api(env('TELEGRAM_BOT_TOKEN'));
    $chat_link = Setting::getSettings('chat_link');
    $chat_link = ($chat_link) ? $chat_link->value : 0;
    $text      = 'Вы успешно оплатили подписку.' . PHP_EOL;

    if ( ! $user->in_chat) {

      $telegram->unbanChatMember([
        'chat_id' => $chat_id,
        'user_id' => $user->id
      ]);

      $text .= 'Ссылка на вступление в чат: ' . $chat_link . PHP_EOL;
    }

    $telegram->sendMessage([
      'chat_id'      => $user->id,
      'text'         => $text
    ]);

    $text = 'Выберите действие';

    $vebinar_buy = Keyboard::inlineButton([
      'text'          => 'Купить вебинары',
      'callback_data' => 'buy_vebinars',
    ]);

    $my_vebinars = Keyboard::inlineButton([
      'text'          => 'Мои покупки',
      'callback_data' => 'my_vebinars',
    ]);

    $reply_markup = new Keyboard();
    $reply_markup->inline();
    $reply_markup->row(
      $vebinar_buy,
      $my_vebinars
    );

    $response = $telegram->sendMessage([
      'chat_id'      => $query->getFrom()->getId(),
      'text'         => $text,
      'reply_markup' => $reply_markup
    ]);
  }

  /**
   * Send vebinar link to user
   */
  public function notice_user(Order $order) {

    $telegram = new Api(env('TELEGRAM_BOT_TOKEN'));
    $products = unserialize($order->products);
    $product  = $products[0];
    $vebinar  = Product::find($product);

    $text  = 'Вы оплатили вебинар "' . $vebinar->title .'"' . PHP_EOL;
    $text .= 'Ссылка на вебинар: ' . $order->description .'"' . PHP_EOL;

    $telegram->sendMessage([
      'chat_id' => $order->telegram_user_id,
      'text'    => $text
    ]);

    $text = 'Выберите действие';

    $vebinar_buy = Keyboard::inlineButton([
      'text'          => 'Купить вебинары',
      'callback_data' => 'buy_vebinars',
    ]);

    $my_vebinars = Keyboard::inlineButton([
      'text'          => 'Мои покупки',
      'callback_data' => 'my_vebinars',
    ]);

    $reply_markup = new Keyboard();
    $reply_markup->inline();
    $reply_markup->row(
      $vebinar_buy,
      $my_vebinars
    );

    $response = $telegram->sendMessage([
      'chat_id'      => $order->telegram_user_id,
      'text'         => $text,
      'reply_markup' => $reply_markup
    ]);

    return redirect()->route('admin.order.edit', $order);
  }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Order;
use App\TelegramUser;
use App\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {

    $users_data = [];
    $users      = TelegramUser::all()->toArray();
    foreach ($users as $user) {

      $users_data[ $user['id'] ] = $user['first_name'] . ' ' . $user['last_name'];
    } 
      
    return view('backend.orders.index', [
      'orders' => Order::orderBy('created_at', 'desc')->paginate(7),
      'users'  => $users_data
    ]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    
    return view('backend.orders.create', [
      'order'    => [],
      'users'    => TelegramUser::all()->toArray(),
      'products' => Product::where('status', '=', 1)->get()->toArray()
    ]);
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    
    $order = Order::create($request->all());

    return redirect()->route('admin.order.edit', $order);
  }

  /**
   * Display the specified resource.
   *
   * @param  \App\Order  $order
   * @return \Illuminate\Http\Response
   */
  public function show(Order $order)
  {
    
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  \App\Order  $order
   * @return \Illuminate\Http\Response
   */
  public function edit(Order $order)
  {
    return view('backend.orders.edit', [
      'order'    => $order,
      'users'    => TelegramUser::all()->toArray(),
      'products' => Product::all()->toArray()
    ]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  \App\Order  $order
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Order $order)
  {
    $order->update($request->except('slug'));

    return redirect()->route('admin.order.edit', $order);
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  \App\Order  $order
   * @return \Illuminate\Http\Response
   */
  public function destroy(Order $order)
  {
    $order->delete();
    
    return redirect()->route('admin.order.index');
  }
}

app/Http/Controllers/Backend/PaymentController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Setting;
use App\Order;
use App\TelegramUser;
use App\Product;

class PaymentController extends Controller
{
  public function handle() {

    // http://77.222.60.8/payment/response?MERCHANT_ID=97957&AMOUNT=15.30&MERCHANT_ORDER_ID=1&SIGN=dgd&us_type=vebiinar

    \Log::info('test');
    \Log::info(print_r($_REQUEST, true));

    $available_ip = ['136.243.38.147', '136.243.38.149', '136.243.38.150', '136.243.38.151', '136.243.38.189', '88.198.88.98'];
    $ip           = isset($_SERVER['HTTP_X_REAL_IP']) ? $_SERVER['HTTP_X_REAL_IP'] : $_SERVER['REMOTE_ADDR'];
    if ( ! in_array($ip, $available_ip)) {
     die('hacking attempt!');
    }

    $merchant_id = Setting::getSettings('merchant_id');
    $merchant_id = ($merchant_id) ? $merchant_id->value : 0;
    $secret_word = 'ignetdapassion';

    $sign = md5($merchant_id.':'.$_REQUEST['AMOUNT'].':'.$secret_word.':'.$_REQUEST['MERCHANT_ORDER_ID']);

    if ($sign != $_REQUEST['SIGN']) {
      die('wrong sign');
    }

    if ( ! isset($_REQUEST['us_type'])) {

      die('wrong request');
    }

    $type     = $_REQUEST['us_type'];
    $amount   = $_REQUEST['AMOUNT'];
    $order_id = $_REQUEST['MERCHANT_ORDER_ID'];

    if ('subscribe' == $type) {

      $subscription_cost = Setting::getSettings('subscription_cost');
      $subscription_cost = ($subscription_cost) ? $subscription_cost->value : 0;
      if ($subscription_cost != $amount) {
        die('wrong amount');
      }

      $teluser = TelegramUser::find($_REQUEST['MERCHANT_ORDER_ID']);
      if ( ! $teluser) {
        die('wrong user id');
      }

      $now = new \DateTime();
      $now->format('Y-m-d H:i:s');

      $teluser->subscribe_date = $now;
      $teluser->sub_notice     = 0;
      $teluser->save();

      NoticeController::subscription_paid($teluser);
    } else {

      $order = Order::find($_REQUEST['MERCHANT_ORDER_ID']);
      if ( ! $order) {
        die('wrong order id');
      }

      if (floatval($amount) < floatval($order->amount)) {
        die('wrong amount');
      }
      
      $order->status = 1;
      $order->save();

      $products      = unserialize($order->products);
      $teluser       = TelegramUser::find($order->telegram_user_id);
      $paid_products = unserialize($teluser->products);
      $paid_products = ( ! is_array($paid_products)) ? [] : $paid_products;
      $result        = array_unique(array_merge($products, $paid_products));

      $teluser->products = serialize($result);
      $teluser->save();

      NoticeController::vebinar_paid($order);
    }

    die('ok');
  }
}

resources/views/backend/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                      <li class="dropdown">
                        <a href="{{ route('admin.index') }}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                          Panel <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu">
                            <li>
                              <a href="{{ route('admin.product.index') }}">Products</a>
                              <a href="{{ route('admin.order.index') }}">Orders</a>
                              <a href="{{ route('admin.telegramuser.index') }}">Users</a>
                            </li>
                        </ul>
                      </li>
                      <li><a href="{{ route('admin.setting.index') }}">Settings</a></li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>