routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::namespace('Backend')->group(function () {
  
  Route::post('/payment/response', 'PaymentController@handle')->name('payment.response');
});

Route::middleware(['auth'])->prefix('admin')->namespace('Backend')->name('admin.')->group(function() {
  
  Route::get('/', 'DashboardController@index')->name('index');
  Route::get('/setting', 'SettingController@index')->name('setting.index');
  Route::post('/setting/store', 'SettingController@store')->name('setting.store');
  Route::post('/setting/setwebhook', 'SettingController@setwebhook')->name('setting.setwebhook');
  Route::post('/setting/getwebhookinfo', 'SettingController@getwebhookinfo')->name('setting.getwebhookinfo');

  Route::resource('/telegramuser', 'TelegramUserController');
  Route::resource('/product', 'ProductController');
  Route::resource('/order', 'OrderController');

  Route::get('/notice/user/{order}', 'NoticeController@notice_user')->name('notice.user');
});

Auth::routes();

Route::match(['post', 'get'], 'register', function() {
  Auth::logout();
  return redirect('/');
})->name('register');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
  protected $fillable = [
    'telegram_user_id',
    'amount',
    'products',
    'status',
    'created_by',
    'modified_by',
    'description'
  ];

  public function setProductsAttribute($value) {

    $this->attributes['products'] = serialize($value);
  }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Order;
use App\TelegramUser;
use App\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {

    $users_data = [];
    $users      = TelegramUser::all()->toArray();
    foreach ($users as $user) {

      $users_data[ $user['id'] ] = $user['first_name'] . ' ' . $user['last_name'];
    } 
      
    return view('backend.orders.index', [
      'orders' => Order::orderBy('created_at', 'desc')->paginate(7),
      'users'  => $users_data
    ]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    
    return view('backend.orders.create', [
      'order'    => [],
      'users'    => TelegramUser::all()->toArray(),
      'products' => Product::where('status', '=', 1)->get()->toArray()
    ]);
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    
    $order = Order::create($request->all());

    return redirect()->route('admin.order.edit', $order);
  }

  /**
   * Display the specified resource.
   *
   * @param  \App\Order  $order
   * @return \Illuminate\Http\Response
   */
  public function show(Order $order)
  {
    
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  \App\Order  $order
   * @return \Illuminate\Http\Response
   */
  public function edit(Order $order)
  {
    return view('backend.orders.edit', [
      'order'    => $order,
      'users'    => TelegramUser::all()->toArray(),
      'products' => Product::all()->toArray()
    ]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  \App\Order  $order
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Order $order)
  {
    $order->update($request->except('slug'));

    return redirect()->route('admin.order.edit', $order);
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  \App\Order  $order
   * @return \Illuminate\Http\Response
   */
  public function destroy(Order $order)
  {
    $order->delete();
    
    return redirect()->route('admin.order.index');
  }
}

resources/views/backend/orders/partials/form.blade.php
<label for="status">Status</label>
<select name="status" class="form-control">

  @if (isset($order->id))
    
    <option value="0" @if (0 == $order->status) selected="" @endif> Awaiting payment</option>
    <option value="1" @if (1 == $order->status) selected="" @endif> Paid</option>
  @else
      
    <option value="0"> Awaiting payment</option>
    <option value="1"> Paid</option>
  @endif
</select>

<label for="telegram_user_id">Сustomer</label>
<select name="telegram_user_id" class="form-control">

  @if (isset($order->id))

    @foreach ($users as $user)
          
    <option value="{{ $user['id'] }}" @if ($user['id'] == $order->telegram_user_id) selected="" @endif> {{ $user['first_name'] . ' ' . $user['last_name'] }}</option>
    @endforeach
  @else

    @foreach ($users as $user)
        
     <option value="{{ $user['id'] }}"> {{ $user['first_name'] . ' ' . $user['last_name'] }}</option>
    @endforeach
  @endif
</select>

<label for="amount">Amount</label>
<input type="number" pattern="[0-9]+([\.,][0-9]+)?" step="0.01" class="form-control" name="amount" placeholder="1.00" value="{{ $order->amount or "" }}" required>

<label for="products">Products</label>
<select name="products[]" class="form-control" required>

  @if (isset($order->id))

    @foreach ($products as $product)
      <option value="{{ $product['id'] }}" @if (in_array($product['id'], unserialize($order->products))) selected="" @endif> {{ $product['title'] }}</option>
    @endforeach
  @else

    @foreach ($products as $product)
      <option value="{{ $product['id'] }}"> {{ $product['title'] }}</option>
    @endforeach
  @endif
</select>

<label for="description">Link</label>
<input type="url" class="form-control" name="description" placeholder="http://vebinar.com" value="{{ $order->description or "" }}" required>

@if (isset($order->description) && '' != $order->description)
  <p> 
    <a class="btn btn-default" href="{{ route('admin.notice.user', $order) }}"><i class="fas fa-envelope"></i> Отправить ссылку пользователю</a>
  </p>
@endif
<br>

<input class="btn btn-primary" type="submit" value="Save">